/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones = 'Europe/Berlin';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    templates: Template;
    gallery: Gallery;
    media: Media;
    'page-views': PageView;
    actions: Action;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    templates: TemplatesSelect<false> | TemplatesSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'page-views': PageViewsSelect<false> | PageViewsSelect<true>;
    actions: ActionsSelect<false> | ActionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('de' | 'en') | ('de' | 'en')[];
  globals: {
    site: Site;
    legal: Legal;
    translations: Translation;
    analytics: Analytics;
  };
  globalsSelect: {
    site: SiteSelect<false> | SiteSelect<true>;
    legal: LegalSelect<false> | LegalSelect<true>;
    translations: TranslationsSelect<false> | TranslationsSelect<true>;
    analytics: AnalyticsSelect<false> | AnalyticsSelect<true>;
  };
  locale: 'de' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * SVG templates next to the drawing area, in this order (drag & drop). Name them in both languages (locale at the top).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates".
 */
export interface Template {
  id: string;
  _order?: string | null;
  /**
   * Shown on hover and read out: “Insert Star”.
   */
  name: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Cards for the fan above the footer – five are drawn at random on every load. Paste a creation's link below to build one.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: string;
  _order?: string | null;
  /**
   * The cutter from above on the card – its alt text comes from Media.
   */
  picture: string | Media;
  /**
   * On the card below the cutter – empty: “Cookie Cutter”.
   */
  name?: string | null;
  /**
   * One of the card colors set in Site – none chosen: the first.
   */
  color?: string | null;
  /**
   * The creation the card was built from – empty for a picture picked by hand.
   */
  link?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * All pictures, each with what it shows.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * What the picture shows – read out instead.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-views".
 */
export interface PageView {
  id: string;
  path: string;
  referrer?: string | null;
  device?: string | null;
  os?: string | null;
  browser?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "actions".
 */
export interface Action {
  id: string;
  name:
    | 'download-3mf'
    | 'download-stl'
    | 'cookie-saved'
    | 'share-open'
    | 'share-link'
    | 'share-image'
    | 'save-image'
    | 'card-created'
    | 'card-turned'
    | 'card-eaten'
    | 'card-download-3mf'
    | 'card-download-stl'
    | 'card-picture'
    | 'svg-import'
    | 'template';
  path?: string | null;
  device?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'templates';
        value: string | Template;
      } | null)
    | ({
        relationTo: 'gallery';
        value: string | Gallery;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'page-views';
        value: string | PageView;
      } | null)
    | ({
        relationTo: 'actions';
        value: string | Action;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates_select".
 */
export interface TemplatesSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  _order?: T;
  picture?: T;
  name?: T;
  color?: T;
  link?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-views_select".
 */
export interface PageViewsSelect<T extends boolean = true> {
  path?: T;
  referrer?: T;
  device?: T;
  os?: T;
  browser?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "actions_select".
 */
export interface ActionsSelect<T extends boolean = true> {
  name?: T;
  path?: T;
  device?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Links in the footer, on the greeting card and in the legal text, the address in the legal text, and the greeting cards' favorite colors.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site".
 */
export interface Site {
  id: string;
  links: {
    /**
     * The footer's “mxwr.de” and the card's “made by”. Keep the utm part – it shows where visits came from.
     */
    website: string;
    /**
     * The footer's “MakerWorld”.
     */
    makerworld: string;
    /**
     * The sun cookie and “Buy me a cookie”.
     */
    donate: string;
    /**
     * Where the source code is.
     */
    source: string;
  };
  /**
   * Shown wherever the legal text has an “Address” block (§ 5 DDG, § 18 MStV).
   */
  address: {
    name: string;
    street: string;
    city: string;
    country: string;
  };
  /**
   * The favorite colors to pick for a greeting card – the cookie's icing, and in its shades the card, its back and its words. The first one is the default. A color's place is its number in card links: add new ones at the end only, don't reorder or delete – sent cards would change color.
   */
  cardColors?:
    | {
        /**
         * As #rrggbb, e.g. #ff5fa8 – or pick it. Below: the card in its shades.
         */
        color: string;
        /**
         * Shown when pointing at it, read out aloud.
         */
        name: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The dialog behind “Imprint & privacy”. Address and links come from “Site”; switch the language at the top.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal".
 */
export interface Legal {
  id: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "translations".
 */
export interface Translation {
  id: string;
  card?: {
    /**
     * DE: gebacken  ·  EN: baked
     */
    baked?: string | null;
    /**
     * DE: Anbeißen  ·  EN: Take a bite
     */
    bite?: string | null;
    /**
     * DE: *klick*  ·  EN: *click*
     */
    click?: string | null;
    /**
     * DE: Lieblingsfarbe  ·  EN: Favorite color
     */
    color?: string | null;
    /**
     * DE: Der Keks aus „{{name}}“  ·  EN: The cookie from “{{name}}”
     */
    cookieAlt?: string | null;
    /**
     * DE: Karte erstellen  ·  EN: Create card
     */
    create?: string | null;
    /**
     * DE: Ausstecher „{{name}}“  ·  EN: Cookie cutter “{{name}}”
     */
    cutterAlt?: string | null;
    /**
     * DE: 3MF herunterladen  ·  EN: Download 3MF
     */
    download?: string | null;
    /**
     * DE: Iss mich  ·  EN: Eat me
     */
    eatMe?: string | null;
    /**
     * DE: gegessen  ·  EN: eaten
     */
    eaten?: string | null;
    /**
     * DE: Ändern  ·  EN: Edit
     */
    edit?: string | null;
    /**
     * DE: Auf dieser Karte ist kein Ausstecher.  ·  EN: There is no cookie cutter on this card.
     */
    empty?: string | null;
    /**
     * DE: Das hat gerade nicht geklappt.  ·  EN: That didn’t work just now.
     */
    failed?: string | null;
    /**
     * DE: karte  ·  EN: card
     */
    fileSuffix?: string | null;
    /**
     * DE: Umdrehen  ·  EN: Turn over
     */
    flip?: string | null;
    /**
     * DE: Zurückdrehen  ·  EN: Turn back
     */
    flipBack?: string | null;
    /**
     * DE: Für {{name}}  ·  EN: For {{name}}
     */
    for?: string | null;
    /**
     * DE: Für dich  ·  EN: For you
     */
    forYou?: string | null;
    /**
     * DE: Von  ·  EN: From
     */
    from?: string | null;
    /**
     * DE: von {{name}}  ·  EN: from {{name}}
     */
    fromName?: string | null;
    /**
     * DE: Dein Name  ·  EN: Your name
     */
    fromPlaceholder?: string | null;
    /**
     * DE: Schreib ein paar Zeilen dazu – auf der Karte laufen sie rund um deinen Ausstecher.  ·  EN: Add a few lines – on the card they run all the way around your cutter.
     */
    intro?: string | null;
    /**
     * DE: Dein Ausstecher wird geformt …  ·  EN: Shaping your cookie cutter …
     */
    loading?: string | null;
    /**
     * DE: Eigenen Ausstecher gestalten  ·  EN: Design your own cutter
     */
    makeOwn?: string | null;
    /**
     * DE: Nachricht  ·  EN: Message
     */
    message?: string | null;
    /**
     * DE: Karte ansehen  ·  EN: View card
     */
    open?: string | null;
    /**
     * DE: Die Karte als Bild – für Instagram, WhatsApp & Co.  ·  EN: The card as a picture – for Instagram, WhatsApp & co.
     */
    pictureHint?: string | null;
    /**
     * DE: Speichern  ·  EN: Save
     */
    pictureSave?: string | null;
    /**
     * DE: Teilen  ·  EN: Share
     */
    pictureShare?: string | null;
    /**
     * DE: Bereit für den 3D-Drucker – Rand aufs Druckbett, ohne Stützen  ·  EN: Ready for the 3D printer – rim on the bed, no supports
     */
    printHint?: string | null;
    /**
     * DE: Deine Karte ist fertig – schick einfach den Link.  ·  EN: Your card is ready – just send the link.
     */
    ready?: string | null;
    /**
     * DE: Nochmal versuchen  ·  EN: Try again
     */
    retry?: string | null;
    /**
     * DE: Ein Ausstecher, nur für dich  ·  EN: A cookie cutter, just for you
     */
    ring?: string | null;
    /**
     * DE: Link teilen  ·  EN: Share link
     */
    send?: string | null;
    /**
     * DE: Ich hab dir einen Ausstecher gemacht:  ·  EN: I made you a cookie cutter:
     */
    shareText?: string | null;
    /**
     * DE: STL  ·  EN: STL
     */
    stl?: string | null;
    /**
     * DE: Eine Karte für dich  ·  EN: A card for you
     */
    title?: string | null;
    /**
     * DE: Eine Karte für {{name}}  ·  EN: A card for {{name}}
     */
    titleFor?: string | null;
    /**
     * DE: An  ·  EN: To
     */
    to?: string | null;
    /**
     * DE: Name  ·  EN: Name
     */
    toPlaceholder?: string | null;
  };
  contact?: {
    /**
     * DE: E-Mail  ·  EN: Email
     */
    email?: string | null;
    /**
     * DE: Das hat nicht geklappt. Bitte versuch es später noch einmal.  ·  EN: That didn't work. Please try again later.
     */
    error?: string | null;
    /**
     * DE: Schreib mir – ich antworte per E-Mail.  ·  EN: Write to me – I'll answer by email.
     */
    intro?: string | null;
    /**
     * DE: Bitte gib deinen Namen, eine gültige E-Mail-Adresse und eine Nachricht an.  ·  EN: Please enter your name, a valid email address and a message.
     */
    invalid?: string | null;
    /**
     * DE: Nachricht  ·  EN: Message
     */
    message?: string | null;
    /**
     * DE: Name  ·  EN: Name
     */
    name?: string | null;
    /**
     * DE: Zu viele Nachrichten – bitte versuch es später noch einmal.  ·  EN: Too many messages – please try again later.
     */
    rateLimited?: string | null;
    /**
     * DE: Senden  ·  EN: Send
     */
    send?: string | null;
    /**
     * DE: Wird gesendet …  ·  EN: Sending …
     */
    sending?: string | null;
    /**
     * DE: Danke! Deine Nachricht ist unterwegs.  ·  EN: Thanks! Your message is on its way.
     */
    sent?: string | null;
    /**
     * DE: Kontakt  ·  EN: Contact
     */
    title?: string | null;
  };
  draw?: {
    /**
     * DE: Pinselstärke  ·  EN: Brush size
     */
    brush?: string | null;
    /**
     * DE: Löschen  ·  EN: Clear
     */
    clear?: string | null;
    /**
     * DE: Loslassen zum Importieren  ·  EN: Release to import
     */
    drop?: string | null;
    /**
     * DE: Radiergummi  ·  EN: Eraser
     */
    eraser?: string | null;
    /**
     * DE: Zeichenfläche vergrößern  ·  EN: Enlarge canvas
     */
    expand?: string | null;
    /**
     * DE: Umriss malen oder SVG hierher ziehen  ·  EN: Draw an outline or drop an SVG here
     */
    hint?: string | null;
    /**
     * DE: Geschlossene Linien werden gefüllt, Formen in Formen ausgeschnitten.  ·  EN: Closed lines get filled, shapes inside shapes cut out.
     */
    hintSub?: string | null;
    /**
     * DE: {{name}} einfügen  ·  EN: Insert {{name}}
     */
    insert?: string | null;
    /**
     * DE: Formen verschieben  ·  EN: Move shapes
     */
    move?: string | null;
    /**
     * DE: Form ziehen · Rahmen aufziehen für mehrere · Ecken drehen & skalieren · Entf löscht  ·  EN: Drag a shape · drag a box to pick several · corners rotate & scale · Del removes
     */
    moveHint?: string | null;
    /**
     * DE: Stift  ·  EN: Pen
     */
    pen?: string | null;
    /**
     * DE: Vorlagen  ·  EN: Templates
     */
    presets?: string | null;
    /**
     * DE: Wiederholen  ·  EN: Redo
     */
    redo?: string | null;
    /**
     * DE: Ausgewählte Form entfernen (Entf)  ·  EN: Remove the selected shape (Del)
     */
    removeSelection?: string | null;
    /**
     * DE: Zeichenfläche verkleinern  ·  EN: Shrink canvas
     */
    shrink?: string | null;
    /**
     * DE: Werkzeuge  ·  EN: Tools
     */
    tools?: string | null;
    /**
     * DE: Rückgängig  ·  EN: Undo
     */
    undo?: string | null;
    /**
     * DE: SVG hochladen  ·  EN: Upload SVG
     */
    upload?: string | null;
  };
  errors_?: {
    /**
     * DE: Aus dieser Form ließ sich kein Ausstecher erzeugen.  ·  EN: Couldn't create a cutter from this shape.
     */
    build?: string | null;
    /**
     * DE: In der Datei wurde keine Form gefunden.  ·  EN: No shape found in this file.
     */
    empty?: string | null;
    /**
     * DE: Geometrie-Engine konnte nicht geladen werden.  ·  EN: The geometry engine could not be loaded.
     */
    engine?: string | null;
    /**
     * DE: Keine gültige SVG-Datei.  ·  EN: Not a valid SVG file.
     */
    invalidSvg?: string | null;
    /**
     * DE: Dein Browser unterstützt kein Canvas.  ·  EN: Your browser does not support canvas.
     */
    noCanvas?: string | null;
    /**
     * DE: Datei konnte nicht gelesen werden.  ·  EN: The file could not be read.
     */
    read?: string | null;
  };
  export?: {
    /**
     * DE: Namen löschen  ·  EN: Clear the name
     */
    clearName?: string | null;
    /**
     * DE: Name deiner Kreation  ·  EN: Name of your creation
     */
    name?: string | null;
    /**
     * DE: Name deiner Kreation, z. B. Herz  ·  EN: Name your creation, e.g. Heart
     */
    namePlaceholder?: string | null;
    /**
     * DE: STL  ·  EN: STL
     */
    stl?: string | null;
    /**
     * DE: 3MF herunterladen  ·  EN: Download 3MF
     */
    threeMf?: string | null;
  };
  footer?: {
    /**
     * DE: Mit PayPal einen Keks spendieren  ·  EN: Buy me a cookie via PayPal
     */
    donateLabel?: string | null;
    /**
     * DE: ’nen Keks  ·  EN: a cookie
     */
    donateMain?: string | null;
    /**
     * DE: Spendier mir  ·  EN: Buy me
     */
    donateTop?: string | null;
    /**
     * DE: Impressum & Datenschutz  ·  EN: Imprint & privacy
     */
    imprint?: string | null;
  };
  gallery?: {
    /**
     * DE: Beispiele  ·  EN: Examples
     */
    label?: string | null;
  };
  hints?: {
    /**
     * DE: Meldet Bambu Studio „invalid config“: einfach OK – die Geometrie ist vollständig. Ohne Meldung geht es über Datei → Import.  ·  EN: If Bambu Studio says “invalid config”, just click OK – the geometry is complete. File → Import avoids the notice.
     */
    bambu?: string | null;
    /**
     * DE: Für Teig am besten lebensmittelechtes Filament. Von Hand lauwarm spülen, nicht in die Spülmaschine: PLA verzieht sich ab etwa 55 °C, und in den Druckrillen bleiben gern Teigreste hängen.  ·  EN: For dough, food-safe filament is best. Wash by hand in lukewarm water, not in the dishwasher: PLA warps from about 55 °C, and dough likes to stick in the print lines.
     */
    foodSafe?: string | null;
    /**
     * DE: PLA, 0,2 mm Schichthöhe  ·  EN: PLA, 0.2 mm layer height
     */
    material?: string | null;
    /**
     * DE: Falz liegt auf dem Druckbett  ·  EN: Rim sits on the print bed
     */
    orientation?: string | null;
    /**
     * DE: In Bambu Studio einfach importieren  ·  EN: Just import it into Bambu Studio
     */
    slicer?: string | null;
    /**
     * DE: Keine Stützen nötig  ·  EN: No supports needed
     */
    supports?: string | null;
    /**
     * DE: Druckhinweise  ·  EN: Printing tips
     */
    title?: string | null;
  };
  jar?: {
    /**
     * DE: Keksleiste schließen  ·  EN: Close the cookie bar
     */
    close?: string | null;
    /**
     * DE: „{{name}}“ aufessen  ·  EN: Eat “{{name}}”
     */
    eat?: string | null;
    /**
     * DE: Frisch gebacken: „{{name}}“  ·  EN: Freshly baked: “{{name}}”
     */
    fresh?: string | null;
    /**
     * DE: Deine Kekse  ·  EN: Your cookies
     */
    label?: string | null;
    /**
     * DE: „{{name}}“ öffnen  ·  EN: Open “{{name}}”
     */
    open?: string | null;
    /**
     * DE: Deine Kekse ({{count}})  ·  EN: Your cookies ({{count}})
     */
    reopen?: string | null;
    /**
     * DE: Als Keks speichern  ·  EN: Save as cookie
     */
    save_?: string | null;
    /**
     * DE: Speichert deine Kreation als Keks in der Keksleiste – so findest du sie wieder.  ·  EN: Keeps your creation as a cookie in the cookie bar – so you find it again.
     */
    saveHint?: string | null;
    /**
     * DE: Gespeichert  ·  EN: Saved
     */
    saved?: string | null;
    /**
     * DE: Deine eigenen – einen hast du gebacken.  ·  EN: Your own – you baked one.
     */
    subtitle_one?: string | null;
    /**
     * DE: Deine eigenen – {{count}} hast du gebacken.  ·  EN: Your own – you baked {{count}}.
     */
    subtitle_other?: string | null;
    /**
     * DE: Diese Seite verwendet Kekse.  ·  EN: This site uses cookies.
     */
    title?: string | null;
    /**
     * DE: Ohne Namen  ·  EN: Untitled
     */
    unnamed?: string | null;
  };
  /**
   * DE: Sprache  ·  EN: Language
   */
  language?: string | null;
  legal?: {
    /**
     * DE: Schließen  ·  EN: Close
     */
    close?: string | null;
  };
  params?: {
    /**
     * DE: Klingenhöhe  ·  EN: Blade height
     */
    bladeHeight?: string | null;
    /**
     * DE: Stegbreite  ·  EN: Bridge width
     */
    bridgeWidth?: string | null;
    /**
     * DE: Innere Formen ausschneiden  ·  EN: Cut out inner shapes
     */
    cutouts?: string | null;
    /**
     * DE: Eine Form innerhalb einer anderen wird zum Loch, verbunden über Stege an der Falz.  ·  EN: A shape inside another becomes a hole, held by bridges at the rim.
     */
    cutoutsHint?: string | null;
    /**
     * DE: Schneide  ·  EN: Cutting edge
     */
    edge?: string | null;
    /**
     * DE: Falz-Höhe  ·  EN: Rim height
     */
    flangeHeight?: string | null;
    /**
     * DE: Falz-Breite  ·  EN: Rim width
     */
    flangeWidth?: string | null;
    /**
     * DE: Spiegeln (für Schrift)  ·  EN: Mirror (for text)
     */
    mirror?: string | null;
    /**
     * DE: Ausgestochen wird mit dem umgedrehten Ausstecher – gespiegelt steht Schrift auf dem Keks richtig herum.  ·  EN: Cookies are cut with the cutter upside down – mirrored, text on the cookie reads the right way round.
     */
    mirrorHint?: string | null;
    /**
     * DE: Zurücksetzen  ·  EN: Reset
     */
    reset?: string | null;
    /**
     * DE: Größe  ·  EN: Size
     */
    size?: string | null;
    /**
     * DE: Lücken schließen  ·  EN: Close gaps
     */
    smoothing?: string | null;
    /**
     * DE: Verjüngung  ·  EN: Taper
     */
    taper?: string | null;
    /**
     * DE: Maße  ·  EN: Dimensions
     */
    title?: string | null;
    /**
     * DE: Wandstärke  ·  EN: Wall
     */
    wall?: string | null;
  };
  preview?: {
    /**
     * DE: Hier erscheint dein Ausstecher.  ·  EN: Your cookie cutter will appear here.
     */
    empty?: string | null;
    /**
     * DE: Lade Geometrie-Engine …  ·  EN: Loading geometry engine …
     */
    loading?: string | null;
    /**
     * DE: Automatisch drehen  ·  EN: Rotate automatically
     */
    rotate?: string | null;
  };
  share?: {
    /**
     * DE: Als Grußkarte  ·  EN: As a greeting card
     */
    asCard?: string | null;
    /**
     * DE: Als Bild  ·  EN: As a picture
     */
    asPicture?: string | null;
    /**
     * DE: Oder als Grußkarte verschenken  ·  EN: Or give it as a greeting card
     */
    cardInvite?: string | null;
    /**
     * DE: Mit deiner Nachricht rund um den Ausstecher  ·  EN: With your message around the cutter
     */
    cardInviteHint?: string | null;
    /**
     * DE: Kopiert  ·  EN: Copied
     */
    copied?: string | null;
    /**
     * DE: Link kopieren  ·  EN: Copy link
     */
    copy?: string | null;
    /**
     * DE: Kreation teilen  ·  EN: Share creation
     */
    creation?: string | null;
    /**
     * DE: Über den Link lässt sich deine Zeichnung öffnen und weiter anpassen.  ·  EN: The link opens your drawing so it can be adjusted further.
     */
    creationText?: string | null;
    /**
     * DE: Ausstecher „{{name}}“ von oben  ·  EN: Cookie cutter “{{name}}” from above
     */
    imageAlt?: string | null;
    /**
     * DE: Cookie Cutter Maker – Ausstecher selbst gestalten und 3D-drucken:  ·  EN: Cookie Cutter Maker – design your own cookie cutters and 3D print them:
     */
    pageText?: string | null;
    /**
     * DE: Bild speichern  ·  EN: Save image
     */
    saveImage?: string | null;
    /**
     * DE: Teilen  ·  EN: Share
     */
    share?: string | null;
    /**
     * DE: Seite teilen  ·  EN: Share page
     */
    sharePage?: string | null;
    /**
     * DE: Schau mal, mein Ausstecher – direkt anpassen und als 3MF/STL herunterladen:  ·  EN: Check out my cookie cutter – tweak it and download it as 3MF/STL:
     */
    text?: string | null;
    /**
     * DE: Text und Link sind in der Zwischenablage – falls die App nur das Bild übernimmt, einfach einfügen.  ·  EN: Text and link are on the clipboard – if the app only takes the image, just paste them.
     */
    textCopied?: string | null;
  };
  steps?: {
    /**
     * DE: Ausstecher  ·  EN: Cutter
     */
    cutter?: string | null;
    /**
     * DE: Form  ·  EN: Shape
     */
    shape?: string | null;
  };
  /**
   * DE: Form malen oder SVG hochladen – raus kommt ein druckfertiger Ausstecher.  ·  EN: Draw a shape or upload an SVG – get a print-ready cookie cutter.
   */
  tagline?: string | null;
  /**
   * DE: Cookie Cutter Maker – Ausstecher selbst gestalten und 3D-drucken  ·  EN: Cookie Cutter Maker – design and 3D-print your own cookie cutters
   */
  title?: string | null;
  /**
   * DE: Maßeinheit  ·  EN: Unit
   */
  unit?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Anonymous page views and actions (no IP, no cookies). The time range in the sidebar applies to every section.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics".
 */
export interface Analytics {
  id: string;
  /**
   * "Off" disables the report. Takes effect without a redeploy.
   */
  reportInterval?: ('off' | 'daily' | 'weekly' | 'monthly') | null;
  /**
   * Set automatically whenever a report has gone out.
   */
  lastDigestAt?: string | null;
  analyticsExcludeToken?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_select".
 */
export interface SiteSelect<T extends boolean = true> {
  links?:
    | T
    | {
        website?: T;
        makerworld?: T;
        donate?: T;
        source?: T;
      };
  address?:
    | T
    | {
        name?: T;
        street?: T;
        city?: T;
        country?: T;
      };
  cardColors?:
    | T
    | {
        color?: T;
        name?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal_select".
 */
export interface LegalSelect<T extends boolean = true> {
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "translations_select".
 */
export interface TranslationsSelect<T extends boolean = true> {
  card?:
    | T
    | {
        baked?: T;
        bite?: T;
        click?: T;
        color?: T;
        cookieAlt?: T;
        create?: T;
        cutterAlt?: T;
        download?: T;
        eatMe?: T;
        eaten?: T;
        edit?: T;
        empty?: T;
        failed?: T;
        fileSuffix?: T;
        flip?: T;
        flipBack?: T;
        for?: T;
        forYou?: T;
        from?: T;
        fromName?: T;
        fromPlaceholder?: T;
        intro?: T;
        loading?: T;
        makeOwn?: T;
        message?: T;
        open?: T;
        pictureHint?: T;
        pictureSave?: T;
        pictureShare?: T;
        printHint?: T;
        ready?: T;
        retry?: T;
        ring?: T;
        send?: T;
        shareText?: T;
        stl?: T;
        title?: T;
        titleFor?: T;
        to?: T;
        toPlaceholder?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        error?: T;
        intro?: T;
        invalid?: T;
        message?: T;
        name?: T;
        rateLimited?: T;
        send?: T;
        sending?: T;
        sent?: T;
        title?: T;
      };
  draw?:
    | T
    | {
        brush?: T;
        clear?: T;
        drop?: T;
        eraser?: T;
        expand?: T;
        hint?: T;
        hintSub?: T;
        insert?: T;
        move?: T;
        moveHint?: T;
        pen?: T;
        presets?: T;
        redo?: T;
        removeSelection?: T;
        shrink?: T;
        tools?: T;
        undo?: T;
        upload?: T;
      };
  errors_?:
    | T
    | {
        build?: T;
        empty?: T;
        engine?: T;
        invalidSvg?: T;
        noCanvas?: T;
        read?: T;
      };
  export?:
    | T
    | {
        clearName?: T;
        name?: T;
        namePlaceholder?: T;
        stl?: T;
        threeMf?: T;
      };
  footer?:
    | T
    | {
        donateLabel?: T;
        donateMain?: T;
        donateTop?: T;
        imprint?: T;
      };
  gallery?:
    | T
    | {
        label?: T;
      };
  hints?:
    | T
    | {
        bambu?: T;
        foodSafe?: T;
        material?: T;
        orientation?: T;
        slicer?: T;
        supports?: T;
        title?: T;
      };
  jar?:
    | T
    | {
        close?: T;
        eat?: T;
        fresh?: T;
        label?: T;
        open?: T;
        reopen?: T;
        save_?: T;
        saveHint?: T;
        saved?: T;
        subtitle_one?: T;
        subtitle_other?: T;
        title?: T;
        unnamed?: T;
      };
  language?: T;
  legal?:
    | T
    | {
        close?: T;
      };
  params?:
    | T
    | {
        bladeHeight?: T;
        bridgeWidth?: T;
        cutouts?: T;
        cutoutsHint?: T;
        edge?: T;
        flangeHeight?: T;
        flangeWidth?: T;
        mirror?: T;
        mirrorHint?: T;
        reset?: T;
        size?: T;
        smoothing?: T;
        taper?: T;
        title?: T;
        wall?: T;
      };
  preview?:
    | T
    | {
        empty?: T;
        loading?: T;
        rotate?: T;
      };
  share?:
    | T
    | {
        asCard?: T;
        asPicture?: T;
        cardInvite?: T;
        cardInviteHint?: T;
        copied?: T;
        copy?: T;
        creation?: T;
        creationText?: T;
        imageAlt?: T;
        pageText?: T;
        saveImage?: T;
        share?: T;
        sharePage?: T;
        text?: T;
        textCopied?: T;
      };
  steps?:
    | T
    | {
        cutter?: T;
        shape?: T;
      };
  tagline?: T;
  title?: T;
  unit?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics_select".
 */
export interface AnalyticsSelect<T extends boolean = true> {
  reportInterval?: T;
  lastDigestAt?: T;
  analyticsExcludeToken?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}